tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk
  - name: terraform
    before: |
      ./bin/terraform.sh
  - name: aws-cli
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh
